-- 코드를 입력하세요
SELECT DATE_FORMAT(RES.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, RES.PRODUCT_ID, RES.USER_ID, RES.SALES_AMOUNT
FROM (  
        SELECT O.SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT
        FROM ONLINE_SALE O
        UNION
        SELECT F.SALES_DATE, F.PRODUCT_ID, IFNULL(NULL,NULL) AS USER_ID, F.SALES_AMOUNT
        FROM OFFLINE_SALE F
     ) RES
WHERE MONTH(RES.SALES_DATE) = '03'
ORDER BY RES.SALES_DATE, RES.PRODUCT_ID, RES.USER_ID