-- 코드를 입력하세요
SELECT INGREDIENT_TYPE,SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF
LEFT OUTER JOIN ICECREAM_INFO
ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC