-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE  CAR_ID IN (
        SELECT C2.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
        WHERE MONTH(C2.START_DATE) >= 8 AND MONTH(C2.START_DATE) <= 10
        GROUP BY C2.CAR_ID
        HAVING 5 <= COUNT(*)
        ) AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC