SELECT DISTINCT C1.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR C1
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY C2 ON C2.CAR_ID = C1.CAR_ID
WHERE C1.CAR_TYPE = '세단' AND MONTH(C2.START_DATE) = '10'
ORDER BY C1.CAR_ID DESC